// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIWIgIDws6xIiB4ngrClMJ44PVE-u-vCY',
    appId: '1:643662839874:web:5d4c86e71aa9e658fceddb',
    messagingSenderId: '643662839874',
    projectId: 'wellqueue-509f7',
    authDomain: 'wellqueue-509f7.firebaseapp.com',
    storageBucket: 'wellqueue-509f7.firebasestorage.app',
    measurementId: 'G-QTXRB6CDFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD58pH96nY9LZIOlHg0whzYv6Mz5ZYEY0Q',
    appId: '1:643662839874:android:5969cbb1aa36b4a3fceddb',
    messagingSenderId: '643662839874',
    projectId: 'wellqueue-509f7',
    storageBucket: 'wellqueue-509f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvvbgchQUZd_-ArGiONjtd642a_AcUSkE',
    appId: '1:643662839874:ios:c6733300b9df2653fceddb',
    messagingSenderId: '643662839874',
    projectId: 'wellqueue-509f7',
    storageBucket: 'wellqueue-509f7.firebasestorage.app',
    iosBundleId: 'com.example.wellQueue',
  );
}
